# Generated by Django 2.2 on 2023-02-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_groupservice_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupService',
            new_name='Group',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='services',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Group'),
        ),
    ]
