# Generated by Django 2.2 on 2023-02-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230206_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
