# Generated by Django 2.2 on 2023-03-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=30, verbose_name='Названия')),
                ('main_text', models.TextField()),
                ('data_blog', models.DateTimeField(auto_now_add=True, verbose_name='data published')),
            ],
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='services',
            name='procedure',
            field=models.CharField(max_length=32, verbose_name='Названия'),
        ),
    ]
